### ISSUE TITLE
eth²

### ISSUE THREAD

**Issue by fasya10** [ethereum-lists/contracts#53]
### Project ID

eth_real

### Project Name

eth

### Github Organization

ff

### Security Contact Email

adikpicu@gmail.com

### Network

Ethereum Mainnet (1)

**Comment by Underskate** [comment]
> ### Project ID
> eth_real
> 
> ### Project Name
> eth
> 
> ### Github Organization
> ff
> 
> ### Security Contact Email
> [adikpicu@gmail.com](mailto:adikpicu@gmail.com)
> 
> ### Network
> Ethereum Mainnet (1)
> 
> ### Contract Addresses
> _No response_
